/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#844d74",
        "primary-light": "#fadaec",
        "primary-dark": "#774167",
        "bubble-logo": "#b596f4",
        "bubble-pink": "#ffd8ef",
        "bubble-sky": "#cdefff",
        lavender: "#e1c8f8",
        "lavender-dark": "#5f4b73",
        surface: "#fcf8fc",
        "surface-strong": "#ffffff",
        "surface-secondary": "#f6f2f8",
        muted: "#605e65",
        "muted-subtle": "#eae7ed",
        heading: "#333238",
        urgent: "#a8364b",
        "accent-pink": "#f9b4e1",
        "accent-plum": "#6b5780",
        "icon-muted": "#8f8c95",
        "body-muted": "#7c7a80",
        "search-icon": "#9da3ae",
        "search-placeholder": "#8b9098",
        "chip-pink": "#fff1f8",
        "chip-pink-text": "#6b5262",
        "chip-sky": "#eef4ff",
        "chip-sky-text": "#4d5d77",
        "chip-neutral": "#f4f5f7",
        "chip-border": "#eef1f4",
        "badge-muted": "#e5e1e9",
      },
      fontFamily: {
        sans: ["Moneygraphy-Rounded"],
        brand: ["MoveSans-Bold"],
      },
    },
  },
  plugins: [],
};
